[platformio]
default_envs = ControlBoard_V6
extra_configs =
    platformio.envs/*.ini

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1
monitor_speed = 250000
upload_speed = 921600
lib_deps =
    https://github.com/gin66/FastAccelStepper.git
